version: 2

project_name: sadr
before:
  hooks:
    - go mod tidy

builds:
  - id: sadr
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    # this name template makes the OS and Arch look clean
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    vendor: "pedrohpereira74"
    homepage: "https://github.com/pedrohpereira74/sadr"
    maintainer: "Pedro"
    description: "Capture code with context. Because snippets without a 'why' are sadr."
    license: "MIT"
    formats:
      - deb
      - rpm

brews:
  - repository:
      owner: pedrohpereira74
      name: homebrew-tap
    directory: Formula
    homepage: "https://github.com/pedrohpereira74/sadr"
    description: "Capture code with context. Because snippets without a 'why' are sadr."
    license: "MIT"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

scoops:
  - repository:
      owner: pedrohpereira74
      name: scoop-bucket
    homepage: "https://github.com/pedrohpereira74/sadr"
    description: "Capture code with context. Because snippets without a 'why' are sadr."
    license: "MIT"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
